from Token_Create import Tkn
from ..Other_Class.Other_Fun import Other_fun

StopWord = Other_fun()
TokensF = Tkn()
Docs = "testing anyway"
Tokens = TokensF.FinalTokens(Docs)

print(StopWord.check_Stop_List(Docs))
Docs = 'THE ALLIES AFTER NASSAU IN DECEMBER 1960, THE US  FIRST PROPOSED TO HELP NATO DEVELOP ITS OWN NUCLEAR STRIKE FORCE . BUT EUROPE MADE NO ATTEMPT TO DEVISE A PLAN . LAST WEEK, AS THEY STUDIED THE NASSAU ACCORD BETWEEN PRESIDENT KENNEDY AND PRIME MINISTER MACMILLAN, EUROPEANS SAW EMERGING THE FIRST OUTLINES OF THE NUCLEAR NATO THAT THE US  WANTS AND WILL SUPPORT . IT ALL SPRANG FROM THE ANGLO US  CRISIS OVER CANCELLATION OF THE BUG-RIDDEN SKYBOLT MISSILE, AND THE US  OFFER TO SUPPLY BRITAIN AND FRANCE WITH THE PROVED POLARIS (TIME, DEC . 28) . THE ONE ALLIED LEADER WHO UNRESERVEDLY WELCOMED THE POLARIS OFFER WAS HAROLD MACMILLAN, WHO BY THUS KEEPING A SEPARATE NUCLEAR DETERRENT FOR BRITAIN HAD SAVED HIS OWN NECK . BACK FROM NASSAU, THE PRIME MINISTER BEAMED THAT BRITAIN NOW HAD A WEAPON THAT " WILL LAST A GENERATION . THE TERMS ARE VERY GOOD . " MANY OTHER BRITONS WERE NOT SO SURE . THOUGH THE GOVERNMENT WILL SHOULDER NONE OF THE $800 MILLION DEVELOPMENT COST OF POLARIS, IT HAS ALREADY POURED $28 MILLION INTO SKYBOLT AND WILL HAVE TO SPEND PERHAPS $1 BILLION MORE FOR A FLEET OF MISSILE-PACKING SUBMARINES . AT BEST, THE BRITISH WILL NOT BE ABLE TO DESIGN, BUILD AND PROVE ITS NUCLEAR FLEET BEFORE 1970, THREE YEARS AFTER BRITAIN\'S BOMBER FORCE HAS PRESUMABLY BECOME OBSOLETE . THEN WHAT ? TORY BACKBENCHERS ARE LOUDLY SKEPTICAL OF WHAT THEY CALL " THE SMALL TYPE " IN THE NASSAU PACT, WHICH STIPULATES THAT BRITAIN'


 